import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';

import Header from '@/components/common/Header';
import Main from '@/components/common/Main';

import './globals.css';

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`bg-body-background ${rubik.className}`}>
        <Header />

        <Main>
          {children}
        </Main>
      </body>
    </html>
  );
};

export default RootLayout;
